### ISSUE TITLE
Please update as soon as possible support ES5.5, thank you

### ISSUE THREAD

**Issue by ytc301** [maliceio/malice-kibana-plugin#4]
Please update as soon as possible support ES5.5, thank you

**Comment by blacktop** [comment]
Is there a specific reason you need 5.5?

**Comment by ytc301** [comment]
The new version of the time series visual builder is enhanced

**Comment by blacktop** [comment]
Nice! So I am trying to re-do this repo over here: https://github.com/malice-plugins/kibana-malice I might just keep it here I can't decide... it IS a plugin, but it is a main compenent of the malice framework... I'll probably keep it here 😖 

That is just a skeleton for now, I will pull over the malice styling and hopefully get time to FINALLY finish the Malice Plugin display to look like how VirusTotal displays things.  

However, just FYI if you go into the malice config you should be able to tell it to use the new versions (just won't have the malice style yet) 

`~/.malice/config/config.toml`

and change it to:

```toml
[database]
  name = "malice-elastic"
  image = "blacktop/elasticsearch:5.5"
...

[ui]
  name = "malice-kibana"
  image = "blacktop/kibana:5.5"
...
```

I'll probably update this to 5.5.0 and update malice to use it tonight too.
